// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Budgets.Domain.Specifications.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("BudgetFullExample", Description="Simulating a real complex budget example to detect missing things in domain previ" +
        "ous to create different layers", SourceFile="Features\\BudgetFullExample.feature", SourceLine=0)]
    public partial class BudgetFullExampleFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "BudgetFullExample.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "BudgetFullExample", "Simulating a real complex budget example to detect missing things in domain previ" +
                    "ous to create different layers", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 5
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Label"});
            table1.AddRow(new string[] {
                        "1",
                        "General Account"});
#line 6
 testRunner.Given("Accounts", ((string)(null)), table1, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Label"});
            table2.AddRow(new string[] {
                        "1",
                        "Payee 1"});
            table2.AddRow(new string[] {
                        "2",
                        "Payee 2"});
#line 9
 testRunner.And("Payees", ((string)(null)), table2, "And ");
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("MayJunExample", SourceLine=13)]
        public virtual void MayJunExample()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("MayJunExample", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 14
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Label",
                            "DateFormat",
                            "Currency"});
                table3.AddRow(new string[] {
                            "1",
                            "MyBudget",
                            "dd/MM/yyyy",
                            "EUR"});
#line 15
 testRunner.Given("Budgets", ((string)(null)), table3, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "BudgetId",
                            "Label"});
                table4.AddRow(new string[] {
                            "1",
                            "1",
                            "Subscriptions"});
                table4.AddRow(new string[] {
                            "2",
                            "1",
                            "Vehicles"});
                table4.AddRow(new string[] {
                            "3",
                            "1",
                            "Savings"});
#line 18
 testRunner.And("GroupCategory associated to budgets", ((string)(null)), table4, "And ");
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "GroupCategoryId",
                            "Label"});
                table5.AddRow(new string[] {
                            "1",
                            "1",
                            "Asisa"});
                table5.AddRow(new string[] {
                            "2",
                            "1",
                            "Netflix"});
                table5.AddRow(new string[] {
                            "3",
                            "1",
                            "Amazon Music"});
                table5.AddRow(new string[] {
                            "4",
                            "1",
                            "Amazon Prime"});
                table5.AddRow(new string[] {
                            "5",
                            "1",
                            "PlayStation Network"});
                table5.AddRow(new string[] {
                            "6",
                            "2",
                            "Kia Ceed Insurance"});
                table5.AddRow(new string[] {
                            "7",
                            "2",
                            "Honda PCX Insurance"});
                table5.AddRow(new string[] {
                            "8",
                            "2",
                            "IVTM Honda PCX"});
                table5.AddRow(new string[] {
                            "9",
                            "2",
                            "IVTM Kia Ceed"});
                table5.AddRow(new string[] {
                            "10",
                            "3",
                            "Holidays"});
                table5.AddRow(new string[] {
                            "11",
                            "3",
                            "Christmas"});
                table5.AddRow(new string[] {
                            "12",
                            "3",
                            "Bicycle"});
#line 23
 testRunner.And("Category associated to GroupCategory", ((string)(null)), table5, "And ");
#line hidden
#line 37
 testRunner.When("Transaction is added to MyBudget on 16/05/2022 to Account General Account, Payee " +
                        "Payee 1, Category Asisa with and amount of 100.12 - EUR", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 38
 testRunner.And("Transaction is added to MyBudget on 18/05/2022 to Account General Account, Payee " +
                        "Payee 2, Category Amazon Prime with and amount of 49.88 - EUR", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 39
 testRunner.And("Assign an amount of 49.88 - EUR at June/2022 to Category Amazon Prime", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 40
 testRunner.Then("GroupCategory with label Subscriptions should have 199.88 available at June/2022", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 41
 testRunner.And("GroupCategory with label Vehicles should have 0.00 available at June/2022", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 42
 testRunner.Then("Category with label Asisa should have 100.12 available at June/2022", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 43
 testRunner.And("Category with label Amazon Prime should have 49.88 available at May/2022", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 44
 testRunner.Then("GroupCategory with label Subscriptions should have 49.88 assigned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 45
 testRunner.And("Category with label Asisa should have 0.00 assigned at June/2022", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 46
 testRunner.And("Category with label Amazon Prime should have 49.88 assigned at June/2022", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
